[package]
name    = "rust_hero"
version = "0.0.1"
authors = ["igorfs10 <igorfs10@gmail.com>"]
repository = "https://github.com/igorfs10/rust_hero"
license = "gpl-v3"
[dependencies]
custom_error = "1.7.1"