[workspace]
members = ["rust_hero_dados", "rust_hero_tui", "rust_hero_gui"]
default-members = ["rust_hero_tui"]
resolver = "2"

[profile.release]
lto = true
opt-level = 3
incremental = true
codegen-units = 1

[profile.dev]
lto = false
opt-level = 0
debug = true
codegen-units = 256