[package]
name    = "rust_hero_dados"
version = "0.0.1"
edition = "2018"
authors = ["igorfs10 <igorfs10@gmail.com>"]
repository = "https://github.com/igorfs10/rust_hero"
license = "gpl-v3"
license-file = "LICENSE"
readme = "README.md"

[lib]
crate-type = ["cdylib", "rlib"]
